name: Update Notion Season Image

on:
  workflow_dispatch:

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: List repository contents
        run: |
          echo "Current folder:"
          pwd
          echo "Files:"
          ls -la
          echo "All files:"
          find . -maxdepth 2 -type f | sort

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          npm init -y
          npm install @notionhq/client dotenv

      - name: Run updater
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: node update-season-image.js
